### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by Jochen-sys** [goxr3plus/Java-Google-Speech-Recognizer#2]
Hey I have a question: Is this code for commercial use allowed or not? I would say yes, because it's the GPL 3.0 licence, but is the GSpeechDuplex also under this licence? Actually it's used in the code and so there shouldn't be any problems, shell there?

**Comment by goxr3plus** [comment]
You can use it for commercial as far as the code I wrote. Now what happens from the side of Google is a different story.

I would suggest you use official Google Speech Api Java Library :)

**Comment by Jochen-sys** [comment]
Ok thanks
